# Generated by Django 4.1.7 on 2023-03-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_user_delete_course_delete_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='fform',
        ),
    ]
