# Generated by Django 4.1.7 on 2023-03-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_remove_reg_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
